### ISSUE TITLE
Loss of power message

### ISSUE THREAD

**Issue by doramelindatunde** [kivancsikert/chicken-coop-door#66]

**Comment by lptr** [comment]
We could use the "last will and testament" feature of MQTT: http://www.steves-internet-guide.com/mqtt-last-will-example/

**Comment by lptr** [comment]
Now we run a Google cloud function every five minutes to check for the heartbeat published to Firebase. See https://github.com/kivancsikert/chicken-coop-door/commit/204a24eb8ebc413968c9022257978fd54845ec9d
